#!/usr/bin/env bash
# List all CocoaPods versions available to podenv

set -e

unset bare
for arg; do
  case "$arg" in
  --bare ) bare=1 ;;
  esac
done

CURRENT_VERSION=$(podenv-version-name || true)

if [ "$CURRENT_VERSION" == "system" ]; then
  echo "* system"
fi

print_version() {
  if [ -n "$bare" ]; then
    echo "$1"
  elif [ "$1" == "$CURRENT_VERSION" ]; then
    echo "* $1 (set by $(podenv-version-origin))"
  else
    echo "  $1"
  fi
}

VERSIONS_DIR="$PODENV_ROOT/versions"

# Installed into ~/.podenv/versions
for path in "$VERSIONS_DIR"/*; do
  if [ -d "$path" ]; then
    print_version "${path##*/}"
  fi
done
