#!/usr/bin/env bash

set -e

if [ -z "$PODENV_ROOT" ]; then
  PODENV_ROOT=$HOME/.podenv
fi
if [ ! -d "$PODENV_ROOT" ]; then
  mkdir "$PODENV_ROOT"
fi
export PODENV_ROOT

find_libexec_path() {
  cd "$(dirname "${BASH_SOURCE[0]}")"
  cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")"
  echo "$PWD/../libexec"
}
export PATH="$(find_libexec_path):$PATH"

usage() {
  echo "Usage: podenv [--version] <command>"
  echo
  echo "  version   Displays the current active CocoaPods version"
  echo "  versions  Lists all installed CocoaPods versions"
  echo "  global    Sets the global version of CocoaPods"
  echo "  install   Installs a version of CocoaPods"
  echo "  uninstall Uninstalls a specific CocoaPods version"
  echo "  exec      Runs an executable with the selected CocoaPods version"
  echo
  echo "Visit https://github.com/kylef/podenv for more info."
}

command="$1"
case "$command" in
"" )
  usage
  exit 1
  ;;
-v | --version )
  exec podenv---version
  ;;
-h | --help )
  usage
  ;;
* )
  command_path="$(command -v "podenv-$command" || true)"
  if ! [ -n "$command_path" ]; then
    echo "no such command \`$command'"
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
