#!/usr/bin/env bash
# Uninstalls a CocoaPods version
# completes

set -e

if [ "$1" = "--complete" ]; then
  exec podenv-versions --bare
fi

VERSION=$1
if [ -z "$VERSION" ] ; then
  echo "Usage: podenv uninstall <version>"
  exit 1
fi

if [ "$VERSION" == "system" ]; then
  echo "$VERSION is uninstallable."
  exit 1
fi

if [ -d "$PODENV_ROOT/versions/$VERSION" ]; then
  VERSION_DIRECTORY="$PODENV_ROOT/versions/$VERSION"
else
  echo "$VERSION is not installed."
  exit 1
fi

if [ -r "$PODENV_ROOT/version" ]; then
  CURRENT_VERSION=$(cat "$PODENV_ROOT/version")
  if [ "$VERSION" == "$CURRENT_VERSION" ]; then
    rm -f "$PODENV_ROOT/version"
  fi
fi

rm -fr "$VERSION_DIRECTORY"
